name: Release Workflow
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read versionName from Gradle
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          if git rev-parse $VERSION >/dev/null 2>&1; then
            echo "Tag $VERSION already exists"
          else
            git tag $VERSION
            git push origin $VERSION
          fi

      - name: Trigger JitPack Build
        run: |
          curl -X GET "https://jitpack.io/com/github/${{ github.repository }}/${{ env.VERSION }}/build.log"