name: JitPack Release
on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Get Android Version
        id: android_version
        run: |
          VERSION=$(grep -oP 'versionName\s*=\s*"\K[^"]+' app/build.gradle.kts)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release Tag
        id: create_tag
        run: |
          VERSION="v${{ steps.android_version.outputs.VERSION }}"
          echo "Creating new tag: $VERSION"
          git tag $VERSION
          git push origin $VERSION
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          generate_release_notes: true
          token: ${{ secrets.GH_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Trigger JitPack Build
        run: |
          # Trigger JitPack build by making a request to the lookup URL
          curl -L "https://jitpack.io/com/github/${{ github.repository }}/${{ steps.create_tag.outputs.version }}/build.log"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}